services:
 frontend:
  build:
   context: ./frontend
  container_name: blog-ui
  ports:
   - 3000:80
  networks:
   - blog-network
  depends_on:
   - backend

 backend:
  build:
   context: ./backend
  container_name: blog-bck
  env_file:
   - ./backend/.env
  networks:
   - blog-network
  depends_on:
    database:
     condition: service_healthy

 database:
  image: mongo:alpine
  container_name: blog-db
  volumes:
   - ./blog-db/db:/data/db
   - ./blog-db/configdb:/data/configdb
  networks:
   - blog-network
  env_file:
   - ./.env 
  healthcheck:
    test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 10s

networks:
 blog-network: