apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: blog
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: eks-local-storage
  local:
    path: /mnt/disks/blog
  nodeAffinity:
   required:
     nodeSelectorTerms:
       - matchExpressions:
           - key: kubernetes.io/hostname
             operator: In
             values:
              - ip-192-168-14-106.ec2.internal
              - ip-192-168-18-217.ec2.internal 
              - ip-192-168-61-89.ec2.internal  
  