kind: Pod
apiVersion: v1
metadata:
  name: blog-pod-frontend
  namespace: blog
  labels:
    app: blog-frontend
spec:
  containers:
  - name: frontend
    image: mukul329/blog-frontend
    ports:
    - containerPort: 80   
    
  