#Cluster IP- but still can use port forward command 
#if using kind cluster
kind: Service
apiVersion: v1 
metadata:
  name: blog-svc 
  namespace: blog
spec:
  type: NodePort
  selector:
    app: blog-frontend
  ports:
    - protocol: TCP
      port: 3000    #Internal port services needed for communication
      targetPort: 80   #container port exposed in dockerfile
      nodePort: 31575  #Port exposed 
