kind: Secret
apiVersion: v1 
metadata:
  name: blog-secret
  namespace: blog
data:
  MONGO_INITDB_ROOT_USERNAME: bWFuZ28=
  MONGO_INITDB_ROOT_PASSWORD: bWFuZ28=   
  JWT_SECRET_KEY: bWFuZ28=
  # CONNECTION_URL: mongodb://blog:blog@blog-db:27017/blog-db?authSource=admin
  # CLIENT_ORIGIN: http://blog-ui:3000
  