kind: Secret
apiVersion: v1 
metadata:
  name: blog-secret
  namespace: blog
data: 
  CONNECTION_URL: mongodb://blog:blog@blog-db:27017/blog-db?authSource=admin
  CLIENT_ORIGIN: http://blog-ui:3000
  