name: Build & push Frontend
on: 
    workflow_dispatch: 
    push:
        paths: .github/workflows/build-ui.yml

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
            
            - name: Docker Set-up
              uses: docker/setup-docker-action@v5
             
            - name: Docker Login
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}  
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_SECRET
            
            - name: Docker Build
              run: cd frontend && docker build -t mukul329/blog-frontend:latest .

            - name: Show image
              run: docker images  

            - name: Docker push
              run: docker push mukul329/blog-frontend:latest  