name: Building & Pushing to Registry
on: 
    workflow_call: 

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }} 

jobs:
    build:
        runs-on: ubuntu-latest
        environment: prod        
        strategy:
            matrix:
                component: [frontend,backend]
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
            
            - name: Docker Set-up
              uses: docker/setup-docker-action@v5

            - name: Docker Login
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_SECRET
            
            - name: Docker Build
              run: cd ${{ matrix.component }} && docker build -t blog-${{ matrix.component }} .

            - name: Image Tagging  
              run: docker tag blog-${{ matrix.component }} $DOCKER_USERNAME/blog-${{ matrix.component }}:git-${{ github.sha }}

            - name: Docker push
              run: docker push $DOCKER_USERNAME/blog-${{ matrix.component }}:git-${{ github.sha }}
