# Goal: To Build both images in one job using matrix Strategy
name: Build & Push
on: 
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest        
        strategy:
            matrix:
                component: [frontend,backend]
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
            
            - name: Docker Set-up
              uses: docker/setup-docker-action@v5

            - name: Trivy Setup
              uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
              with:
                 cache: true
                 version: v0.74.0  
             
            - name: Docker Login
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}  
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_SECRET
            
            - name: Docker Build
              run: cd ${{ matrix.component }} && docker build -t $DOCKER_USERNAME/blog-${{ matrix.component }}:latest .

            - name: Show image
              run: docker images  

            - name: Scan Images
              run: trivy image --exit-code 1 $DOCKER_USERNAME/blog-${{ matrix.component }}:latest

            - name: Docker push
              run: docker push mukul329/blog-${{ matrix.component }}:latest          