name: Continuous Integration
on:
    push:
        branches: main
    pull_request: 
        
jobs:
    code-scanning:
        uses: ./.github/workflows/code-scan.yml
        secrets: inherit    
        
    image-scanning:
        uses: ./.github/workflows/build.yml    
        secrets: inherit
        needs: code-scanning
        
    Push-to-Registry:
        uses: ./.github/workflows/push.yml  
        secrets: inherit  
        needs: image-scanning
