name: Code Scanning
on:
  workflow_call: 

jobs:
    lint:
        uses: ./.github/workflows/code-lint.yml
              
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml
        secrets: inherit
    
    Dependency-Scan:
        uses: ./.github/workflows/deps.yml
    
    Sonarqube-Scan:
        uses: ./.github/workflows/sonar.yml  
        secrets: inherit  
        
    # Security-Scan:
        
        
    
    # Unit-Test:
        