name: Code Linting & Test
on:
    workflow_call: 

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: Show directory
              run:  ls -al 

            - name: Install Module 
              run: cd frontend && yarn && ls -al

            - name: Show directory
              run:  ls -al
              
            - name: Run Linter
              run: cd frontend && yarn lint && ls -al
            
            - name: Show directory
              run:  ls -al  