name: Dependency Checker
on:
    workflow_call: 

permissions:
  contents: read

jobs:
    Dependency_Scan:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: 'Dependency Review'
              uses: actions/dependency-review-action@v5 
              with:
                base-ref: ${{ github.event.before }}
                head-ref: ${{ github.event.after }}

            - name: OWASP Depcheck
              uses: dependency-check/Dependency-Check_Action@main
              id: Depcheck
              with:
                project: 'test'
                path: '.'
                format: 'HTML'
                out: 'reports'

            - name: Upload Test results
              uses: actions/upload-artifact@master
              with:
               name: Depcheck report
               path: ${{github.workspace}}/reports    

