name: Code Linting
on:
    workflow_call: 

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
              with:
               fetch-depth: 0

            - name: Linting Workflows YML
              uses: raven-actions/actionlint@v2  
              with:
                files: ".github/workflows/*.yml"

            - name: Super-linter
              uses: super-linter/super-linter@v8.7.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
              continue-on-error: true

            - name: Install Module 
              run: cd frontend && yarn && ls -al
              
            - name: Run Linter
              run: cd frontend && yarn lint && ls -al