name: SBOM Analysis
on:
    workflow_call: 
jobs:
    sbom-scan:
        runs-on: ubuntu-latest
        permissions: 
          security-events: write
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Generate SBOM (Syft)
              uses: anchore/sbom-action@v0
              with:
                path: .
                format: 'cyclonedx-json'
                output-file: 'sbom.cyclonedx.json'
                
            - name: Archive SBOM Artifact
              uses: actions/upload-artifact@v4
              with:
                name: software-bill-of-materials
                path: sbom.cyclonedx.json  

            - name: Scan SBOM
              uses: anchore/scan-action@v7
              id: scan
              with:
                sbom: 'sbom.cyclonedx.json'
                fail-build: false
                severity-cutoff: 'high'    

            - name: Upload vulnerability report
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: ${{ steps.scan.outputs.sarif }}    