name: Repository Scanning
on:
  workflow_call:
jobs:
  scan:
    runs-on: ubuntu-24.04
    permissions:
      contents: read          # Required to checkout and read repo files
      security-events: write  # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy Setup
        uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
        with:
           cache: true
           version: v0.74.0

      - name: Run Trivy vulnerability scanner in repo mode
        run: trivy fs --scanners vuln,secret,misconfig --format sarif -o trivy-results.sarif .
    #     uses: aquasecurity/trivy-action@v0.36.0
    #     with:
    #       scan-type: 'fs'
    #       ignore-unfixed: true
    #       format: 'sarif'
    #       output: 'trivy-results.sarif'
    #       severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'