name: Secrets Scanning
on:
    workflow_call: 
  
jobs:
  scan:
    runs-on: ubuntu-24.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
        with: 
          fetch-depth: 0

      - name: Gitleak Scan   
        uses: gitleaks/gitleaks-action@v3
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}