name: Setting up servers
on:
    workflow_call: 

permissions:
  contents: read 

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
